# Generated by Django 5.2.9 on 2026-01-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan sana'),
        ),
    ]
